BITMAKER-1804: Rename Bitmaker Cloud and Scraping Product to Estela
bitmakerla/bitmaker-entrypoint pull request #12
Opened 2022-06-19 23:41 UTC by Adriana618

## Ticket
- https://tasks.bitmaker.dev/issues/1804
## Description
- Renamed Bitmaker (Cloud) and Scraping Product to Estela in all repo.

2022-06-20 01:59 UTC, rodp63 requested changes
We should also change the folder name, from `bm_scrapy` to `estela`. This change implies changing the imports in all the files.

2022-06-20 01:59 UTC, rodp63 commented on README.md
> +# Estela Entrypoint
Are we all sure that this is the name? 😅

2022-06-20 01:59 UTC, rodp63 commented on tests/test_env.py
> +        "BM_API_HOST": "http://estela-api.com",
The `BM` prefix of the env variables refers to `BitMaker`, we should use now `ESTELA` as the prefix. Please check all the files for the presence of env varriables. Take into account that this change implies a change in the API engine (function to start jobs).

2022-06-20 21:00 UTC, rodp63 requested changes

2022-06-20 21:00 UTC, rodp63 commented on bm_scrapy/env.py
>          "UNIQUE": msg["unique"],
We should use the prefix in all the variables, so that is standardized. Please don’t forget to change later the `job_manager` in the API module. A more descriptive name should be helpful as well, what do we mean by `UNIQUE`?

2022-06-20 21:00 UTC, rodp63 commented on bm_scrapy/middlewares.py
> +from estela_scrapy.utils import parse_time
This will not work since we didn’t change the folder name, from `bm_scrapy` to `estela_scrapy`.

2022-06-20 22:46 UTC, Adriana618 commented on bm_scrapy/env.py
>          "UNIQUE": msg["unique"],
UNIQUE, means Unique Collection.

2022-06-21 00:56 UTC, rodp63 commented on bm_scrapy/env.py
>          "UNIQUE": msg["unique"],
So why don't we use the name `ESTELA_UNIQUE_COOLLECTION`? Variables should be as descriptive as possible.

2022-06-21 01:02 UTC, rodp63 requested changes
Please resolve the conversations and conflicts. The tests are failing too, please run them with `pytest` and make the appropriate changes 👍 [UPD] Two tests failed because we didn’t add the field `UNIQUE` in the expected results: 

https://github.com/bitmakerla/estela-entrypoint/blob/BITMAKER-1804/tests/test_env.py#L43
https://github.com/bitmakerla/estela-entrypoint/blob/BITMAKER-1804/tests/test_main.py#L40

2022-06-22 15:35 UTC, rodp63 requested changes

2022-06-22 15:35 UTC, rodp63 commented on estela_scrapy/extensions.py
> +            "unique": os.getenv("ESTELA_UNIQUE"),
Please use `ESTELA_UNIQUE_COLLECTION`

2022-06-22 23:27 UTC, rodp63 approved these changes
This is ready to merge, good work 👍

2022-06-23 00:08 UTC, merged