BITMAKER-1997: Add send logs to kafka from entrypoint
bitmakerla/bitmaker-entrypoint pull request #17
Opened 2022-08-17 16:12 UTC by Adriana618

## Ticket
- https://tasks.bitmaker.dev/issues/1997

## Description
- Add Loghandler to send python logs to kafka.
- Add LogObserver to send scrapy logs to kafka.
- Add StdoutLogger to send stderr logs to kafka.

2022-08-17 17:36 UTC, rodp63 requested changes
Please apply the black style

2022-08-17 17:36 UTC, rodp63 commented on estela_scrapy/log.py
> +            msg = "%s\n%s" % (why, msg)
Why are we using this notation?

2022-08-17 17:36 UTC, rodp63 commented on estela_scrapy/log.py
> +        import boto
why do we need boto?

2022-08-18 21:18 UTC, Adriana618 commented on estela_scrapy/log.py
> +            msg = "%s\n%s" % (why, msg)
Changed.

2022-08-18 21:18 UTC, Adriana618 commented on estela_scrapy/log.py
> +        import boto
Removed.

2022-08-19 14:44 UTC, rodp63 approved these changes
Seems good

2022-08-19 19:06 UTC, merged