BITMAKER-964: update state of jobs in API
bitmakerla/bitmaker-entrypoint pull request #5
Opened 2021-07-26 11:21 UTC by renato262

#### Ticket url(s):
- http://tasks.bitmaker.la/issues/964

#### Description:
- Lint code
- Add requirements
- Add update status requests in signals

#### Checklist:
- [X] Check that only one commit is added in the PR with the correct format
- [X] Rebase my branch
- [X] Run `make test`

2021-07-26 17:02 UTC, rodp63 requested changes

2021-07-26 17:02 UTC, rodp63 commented on README.md
>  - `JOB_INFO`: Dictionary with this fields:
Update the fields of `JOB_INFO`

2021-07-27 13:06 UTC, renato262 commented on README.md
>  - `JOB_INFO`: Dictionary with this fields:
Fixed

2021-07-27 15:32 UTC, rodp63 approved these changes

2021-07-27 15:34 UTC, merged